<footer class="container spacer-double-md py-2">
    <div class="row align-items-md-center">
        <div class="col-md-4 mb-4 mb-md-0">
            {{-- <div class="d-flex align-items-center">
                <p class="font-size-14  mb-0"><span class="text-muted">	{{ getSetting('frontend_copyright_text')}} {{ date('Y') }} {{ config('app.name') }}
                <br>Designed & Developed by</span> 
                    <a href="https://121.page/" class="text-dark" target="_blank">
                        {{ __('121.page')}}
                    </a>
                </p>
            </div> --}}
        </div> 
        <div class="col-sm-6 col-md-4 mb-4 mb-sm-0">
            <ul class="list-inline list-group-flush  text-md-center mb-0 mn-top">
                <li class="list-inline-item px-2">
                    <a class="list-group-item-action" href="{{ url('/page/terms') }}">Terms</a>
                </li>
                <li class="list-inline-item px-2">
                    <a class="list-group-item-action" href="{{ url('/page/data-privacy') }}">Privacy</a>
                </li>
            </ul>
        </div>
        <div class="col-sm-6 col-md-4">
            @if(getSetting('show_social_links') == 1)
            <ul class="list-inline text-sm-right mb-0 font-size-14 mn-top">
                @if(getSetting('facebook_link'))
                <li class="list-inline-item px-2">
                    <a class="list-group-item-action " target="_blank" href="{{ getSetting('facebook_link') }}">
                        <span class="fab fa-facebook-f "></span>
                    </a>
                </li>
                @endif
                @if(getSetting('instagram_link'))
                <li class="list-inline-item px-2">
                    <a class="list-group-item-action " target="_blank" href="{{ getSetting('instagram_link') }}">
                        <span class="fab fa-instagram "></span>
                    </a>
                </li>
                @endif
                @if(getSetting('twitter_link'))
                <li class="list-inline-item px-2">
                    <a class="list-group-item-action " target="_blank" href="{{ getSetting('twitter_link') }}">
                        <span class="fab fa-twitter "></span>
                    </a>
                </li>
                @endif
                @if(getSetting('linkedin_link'))
                <li class="list-inline-item px-2">
                    <a class="list-group-item-action " target="_blank" href="{{ getSetting('linkedin_link') }}">
                        <span class="fab fa-linkedin"></span>
                    </a>
                </li>
                @endif
            </ul>
            @endif
        </div>
    </div>
    {{-- <div class="row mt-5 align-items-center "> 
        <div class="col text-lg-center">
            <p class="font-size-12 text-muted mb-0">Font generated by <a class="text-dark" href="https://www.flaticon.com">flaticon.com</a><br> Under <a class="text-dark" href="http://creativecommons.org/licenses/by/3.0/">CC: </a><a class="text-dark" data-file="001-toast" href="http://www.flaticon.com/authors/eucalyp">eucalyp</a>
            </p>
        </div>
    </div> --}}
</footer>